import {NgModule} from '@angular/core';
import {NzIconModule, provideNzIcons} from 'ng-zorro-antd/icon';

import {
  ArrowLeftOutline,
  ArrowRightOutline,
  AppstoreOutline,
  BgColorsOutline,
  BuildOutline,
  CalculatorOutline,
  CalendarOutline,
  CarOutline,
  CheckCircleOutline,
  ClockCircleOutline,
  CopyOutline,
  CreditCardOutline,
  DashboardOutline,
  DeleteOutline,
  DownOutline,
  DownloadOutline,
  EnvironmentOutline,
  EyeInvisibleOutline,
  EyeOutline,
  FileDoneOutline,
  FileTextOutline,
  FilterOutline,
  HistoryOutline,
  IdcardOutline,
  InboxOutline,
  InfoCircleOutline,
  LayoutOutline,
  LockOutline,
  LogoutOutline,
  MailOutline,
  MenuOutline,
  MenuFoldOutline,
  MenuUnfoldOutline,
  MessageOutline,
  MinusCircleOutline,
  PartitionOutline,
  PlayCircleOutline,
  PlusOutline,
  PercentageOutline,
  ProjectOutline,
  ReloadOutline,
  RiseOutline,
  SafetyCertificateOutline,
  SettingOutline,
  SolutionOutline,
  StopOutline,
  SyncOutline,
  TeamOutline,
  TruckOutline,
  UnorderedListOutline,
  UserOutline,
  UserSwitchOutline,
  UsergroupAddOutline,
  WalletOutline
} from '@ant-design/icons-angular/icons';

const icons = [
  ArrowLeftOutline,
  ArrowRightOutline,
  AppstoreOutline,
  BgColorsOutline,
  BuildOutline,
  CalculatorOutline,
  CalendarOutline,
  CarOutline,
  CheckCircleOutline,
  ClockCircleOutline,
  CopyOutline,
  CreditCardOutline,
  DashboardOutline,
  DeleteOutline,
  DownOutline,
  DownloadOutline,
  EnvironmentOutline,
  EyeInvisibleOutline,
  EyeOutline,
  FileDoneOutline,
  FileTextOutline,
  FilterOutline,
  HistoryOutline,
  IdcardOutline,
  InboxOutline,
  InfoCircleOutline,
  LayoutOutline,
  LockOutline,
  LogoutOutline,
  MailOutline,
  MenuOutline,
  MenuFoldOutline,
  MenuUnfoldOutline,
  MessageOutline,
  MinusCircleOutline,
  PartitionOutline,
  PlayCircleOutline,
  PlusOutline,
  PercentageOutline,
  ProjectOutline,
  ReloadOutline,
  RiseOutline,
  SafetyCertificateOutline,
  SettingOutline,
  SolutionOutline,
  StopOutline,
  SyncOutline,
  TeamOutline,
  TruckOutline,
  UnorderedListOutline,
  UserOutline,
  UserSwitchOutline,
  UsergroupAddOutline,
  WalletOutline
];

@NgModule({
  imports: [NzIconModule],
  exports: [NzIconModule],
  providers: [
    provideNzIcons(icons)
  ]
})
export class IconsProviderModule {
}
